// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk09yE12hTfKv2yEvgbobu69XyYwaoMZ0',
    appId: '1:55110423556:web:a053b5c1c1dd08b0fcd151',
    messagingSenderId: '55110423556',
    projectId: 'heyidk-377f0',
    authDomain: 'heyidk-377f0.firebaseapp.com',
    databaseURL: 'https://heyidk-377f0-default-rtdb.firebaseio.com',
    storageBucket: 'heyidk-377f0.appspot.com',
    measurementId: 'G-0HYHWJXZ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMZXi6EZFFlE4oNSgP8OJ2Fp0LPgCz7w',
    appId: '1:55110423556:android:618ce2d89226a850fcd151',
    messagingSenderId: '55110423556',
    projectId: 'heyidk-377f0',
    databaseURL: 'https://heyidk-377f0-default-rtdb.firebaseio.com',
    storageBucket: 'heyidk-377f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuuvOmYbi8siyzJ0_blPSt38WZJYBans',
    appId: '1:55110423556:ios:9d66c5870cd55987fcd151',
    messagingSenderId: '55110423556',
    projectId: 'heyidk-377f0',
    databaseURL: 'https://heyidk-377f0-default-rtdb.firebaseio.com',
    storageBucket: 'heyidk-377f0.appspot.com',
    iosBundleId: 'com.belindaapp.goldBug',
  );
}
